module.exports = {
  plugin: ["typedoc-material-theme"],
  themeColor: "#108be0",
  entryPoints: ["src/index.ts"],
  entryPointStrategy: "Expand",
  out: "docs",
  name: "ConnectedXM Admin SDK",
  navigationLinks: {
    Github: "http://github.com",
    Admin: "http://admin.connectedxm.com",
  },
  navigation: {
    includeCategories: true,
    includeGroups: true,
    includeFolders: false,
  },
  categorizeByGroup: true,
  groupOrder: [
    "Accounts",
    "Activities",
    "Advertisements",
    "Announcements",
    "Benefits",
    "Contents",
    "Email-receipts",
    "Events",
    "Groups",
    "Images",
    "Imports",
    "Interests",
    "Invoices",
    "Levels",
    "Organization",
    "Reports",
    "Self",
    "Series",
    "Sponsorships",
    "Streams",
    "Subscriptions",
    "Support Tickets",
    "Tiers",
    "Videos",
    "*",
  ],
  categoryOrder: ["Hooks", "Queries", "Keys", "Setters", "*"],
  visibilityFilters: {},
  hideGenerator: true,
  hideParameterTypesInTitle: true,
  githubPages: true,
  cname: "admin-sdk.connectedxm.com",
  searchCategoryBoosts: {
    Hooks: 2,
    Queries: 1.5,
  },
};
